typography_spectrum: 0.6623712447471917
color:
  brandStrength: 0.5986357782967389
  lightness: 0.5318393677007407
  saturation: 0.0566009720787406
  rhythmicContrast: 0.5514410338364542
  brandColors:
    - '#FFFFFF'
    - '#65A1E7'
    - '#263053'
    - '#A9755F'
    - '#D8A66A'
layout_spectrum: 0.3258228248450905
name: Longevity Voice
title: Longevity Voice
